### ISSUE TITLE
TERRA-56 ⁃ Crash when creating an Astra DB (only) with v2.1.0-beta

### ISSUE THREAD

**Issue by jdavies** [datastax/terraform-provider-astra#95]
Hi there,

I'm running Terraform 1.1.18 with the 2.1.0-beta version of the Astra plugin. When I create my database (using scripts that are largely the same as they were when using the non-beta version of the plugin) I get a crash error.

You can find all of my scripts on GitHub here: https://github.com/jdavies/cdc_demo

Interestingly, when I check the Astra dashboard, the DB is created and becomes Active as usual. Possibly this crash bug in the clean-up phase of the provider?

### Terraform Version
1.1.8

### Affected Resource(s)
Please list the resources as a list, for example:

* astra_database

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/datastax/astra" {
  version     = "2.1.0-beta"
  constraints = "2.1.0-beta"
  hashes = [
    "h1:GaxkLkZmOjnst3BbS6J8xx9R1CwxXjYtSPeLy3yWrPg=",
    "zh:03c407ae9b3d871d0414dd778ff08f2b52224b3d91af058edb651dc9d59f1eae",
    "zh:2f208fa81a4b88600a8c31a6bf0d5efcddacd8dc8756bb65fe00538412b18918",
    "zh:38ea692bd08c7379de15003bc22ebb1f09564d1941cd40972540f7c08f86c890",
    "zh:454350e7cef1cdf3cc1e1092fc56056ac60d9a4b2b227edf99f1be5144cd426c",
    "zh:59848306fcd5cb6b4c1d62303be12f273e93eab88b906bc81e990dbaf7cba808",
    "zh:9b5fec85343bd62fb8c46c02e81d2750a568791a9aef277e061fc62c76d3e78a",
    "zh:9df50eb4649b0f289a67c0721a43e94e7e556e25b01892b022118fe6f25018f9",
    "zh:cd343264e0e90199934e2394ed9082fff4296649cf900f4e28f4d6cd46367376",
    "zh:cea98b96bbc60d65091a44d40250c8a643879a91d779742d030c55441b9cafe6",
    "zh:cfabacd27d7f0e0748d5fe6d5087ff9f26a567a43cf1614c1030233d84faf7c0",
    "zh:e46442dd8c9f979ccabfe391daa230fdec6c974fa673d384c6f27b74e70e7df4",
    "zh:ec0014860a601e7bf87a9a0c1921ef71bb0a3be0e017bf5ab8faa20f5fcedbfb",
    "zh:f5a67368b32555af8bad2433d9e3119c6b41ac2221eddc21aa4af23b9c953d31",
  ]

```

### Debug Output
```
goroutine 84 [running]:
reflect.Value.IsNil(...)
	reflect/value.go:1086
github.com/mitchellh/mapstructure.(*Decoder).decodeSlice(0xc000630110, 0x0, 0x0, 0x18b3ea0, 0xc00058e2b0, 0x18a08c0, 0xc0007c2168, 0x197, 0x8, 0x8)
	github.com/mitchellh/mapstructure@v1.4.3/mapstructure.go:1091 +0x10ad
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000630110, 0x0, 0x0, 0x18b3ea0, 0xc00058e2b0, 0x18a08c0, 0xc0007c2168, 0x197, 0xc0007c2168, 0x197)
	github.com/mitchellh/mapstructure@v1.4.3/mapstructure.go:469 +0x836
github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc000630110, 0x18b3ea0, 0xc00058e2b0, 0x0, 0xc0007c2168)
	github.com/mitchellh/mapstructure@v1.4.3/mapstructure.go:398 +0xf0
github.com/mitchellh/mapstructure.Decode(0x18b3ea0, 0xc00058e2b0, 0x1881940, 0xc0007c2168, 0x1, 0x19f3284)
	github.com/mitchellh/mapstructure@v1.4.3/mapstructure.go:302 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc0007c26d8, 0xc00058e3c0, 0x1, 0x1, 0x18b3ea0, 0xc00058e2b0, 0x1, 0x19f3284)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/field_writer_map.go:126 +0xd2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc0007c26d8, 0xc00058e3c0, 0x1, 0x1, 0x18b3ea0, 0xc00058e2b0, 0x1, 0x1)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/field_writer_map.go:103 +0xd9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc0007c26d8, 0xc00058e3c0, 0x1, 0x1, 0x18b3ea0, 0xc00058e2b0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/field_writer_map.go:89 +0x3f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0006e6e00, 0x19f3284, 0x7, 0x18b3ea0, 0xc00058e2b0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource_data.go:227 +0x1df
github.com/datastax/terraform-provider-astra/v2/internal/provider.setDatabaseResourceData(0xc0006e6e00, 0xc0002c00e0, 0xc0007c4c00, 0xc00035c0c0)
	github.com/datastax/terraform-provider-astra/v2/internal/provider/resource_database.go:489 +0x114
github.com/datastax/terraform-provider-astra/v2/internal/provider.waitForDatabaseAndUpdateResource.func1(0x2)
	github.com/datastax/terraform-provider-astra/v2/internal/provider/resource_database.go:469 +0x62a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/resource/wait.go:27 +0x5b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc00061e060, 0xc0000dc1c0, 0xc000044240, 0xc0000e60c0, 0xc000432040, 0xc000432038)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/resource/state.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/resource/state.go:83 +0x1c6

Error: The terraform-provider-astra_v2.1.0-beta plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
Should not report a crash

### Actual Behavior
It created the DB successfully, but then the plugin crashes

### Steps to Reproduce
See the readme.md on my GitHub project. The crash occurs when you apply the plan

1. `terraform apply`

### Important Factoids
No

### References
I'm not aware of any.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-56) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-56
┆priority: Major

**Comment by jdavies** [comment]
FYI - this is still happening. I see the DB created in the Astra web UI. However, when iI run the `terraform output` command, the only variable value that I see being set is the organization ID. My script also should show the DB ID and many other generated artifacts from the `apply`.  I am happy to share my scripts if that helps.
